openapi: 3.0.0
info:
  title: ISO 20022 PACS API
  description: |
    # Brief
    
    This is a proof-of-concept for a ISO 20022 Payment Clearing and Settlement (PACS) REST API based on the ISO 20022 organization's whitepaper
    
    # Messages
    
    The following messages have been mapped into this specification:
    
    * FI to FI Customer Credit Transfer (PACS.008.001.07)
    * FI to FI Payment Reversal (PACS.007.001.08)
    * Status (PACS.002.001.09)
    
    Note that these are mapped using a generator as a first pass and further refinement is possible
    
    # Responses
    
    All endpoints are specified to return a Payment Status message (PACS.002.001.09). However, consumers can also receive HTTP response codes based on well-known scenarios. HTTP response codes communicate the success or failure of the request and **no business scenarios are implied by these response codes unless they accompanied by a Payment Status message**
    
    # Callbacks
    
    All request bodies encapsulate a callback URL, allowing out-of-band Payments Status messages to be sent to consumers:
    
    * Each PACS message is wrapped in a property/element that specifies the callback URL
    * The specification uses a `Callback` object from OpenAPI 3.0 to pluck this from the request body
    
    At present this is set to `required: true` and specified per request as a means of demonstrating how flexible the functionality is i.e. it would be possible to provide dedicated endpoints using the message context to drive this. However, there are options to use a single webhook or only part of the message context e.g. a unique identifier concatenated to the callback URL
    
  version: 0.0.1
paths:
  /payments/credits:
    post:
      summary: pacs.008.001.07 - Initiate a FI to FI credit transfer
      description: Credit transfer message
      tags:
      - FI to FI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PACS00800107'
          text/xml:
            schema:
              $ref: '#/components/schemas/PACS00800107'
      responses:
        201:
          $ref: '#/components/responses/PaymentStatus'
        401:
          description: Not authorised
        403:
          description: Not authorised for this resource
        429:
          description: Exceed rate limits for resource
      callbacks:
        PaymentStatus:
          '{$request.body#/callbackUrl}':
            post:
              requestBody:
                $ref: '#/components/requestBodies/PaymentStatusCallback'
              responses:
                200:
                  description: OK
  /payments/reversal:
    post:
      summary: pacs.007.001.08 - Initiate a FI to FI payment reversal
      description: Initiate a payment reversal
      tags:
      - FI to FI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PACS00700108'
          text/xml:
            schema:
              $ref: '#/components/schemas/PACS00700108'
      responses:
        201:
          $ref: '#/components/responses/PaymentStatus'
        401:
          description: Not authorised
        403:
          description: Not authorised for this resource
        429:
          description: Exceed rate limits for resource
      callbacks:
        PaymentStatus:
          '{$request.body#/callbackUrl}':
            post:
              requestBody:
                $ref: '#/components/requestBodies/PaymentStatusCallback'
              responses:
                200:
                  description: OK
components:
  callbacks:
    PaymentStatus:
      '{$request.body#/callbackUrl}':
        post:
          requestBody:
            $ref: '#/components/requestBodies/PaymentStatusCallback'
          responses:
            '200':
              description: OK
  requestBodies:
    PaymentStatusCallback:
      required: true
      description: Further payment status information following initial response
      content:
        application/xml:
          schema:
            $ref: pacs.002.001.09.json#/components/schemas/Document
        application/json:
          schema:
            $ref: pacs.002.001.09.json#/components/schemas/Document
  responses:
    PaymentStatus:
      description: Payment Status response body
      content:
        application/xml:
          schema:
            $ref: pacs.002.001.09.json#/components/schemas/Document
        application/json:
          schema:
            $ref: pacs.002.001.09.json#/components/schemas/Document
  securitySchemes:
    apiKey:
      name: apiKey
      description: API key generated by an API gateway
      type: apiKey
      in: header
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.example.nowhere/token'
          scopes:
            all: Authority to make any request
  schemas:
    PACS00200109:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.002.001.09.json#/components/schemas/Document
    PACS00300107:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.003.001.07.json#/components/schemas/Document
    PACS00400108:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.004.001.08.json#/components/schemas/Document
    PACS00700108:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.007.001.08.json#/components/schemas/Document
    PACS00800107:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.008.001.07.json#/components/schemas/Document
    PACS00900107:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          "$ref": pacs.009.001.07.json#/components/schemas/Document
    PACS01000102:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.010.001.02.json#/components/schemas/Document
    PACS02800102:
      type: object
      required:
      - callbackUrl
      - document
      properties:
        callbackUrl:
          type: string
        document:
          $ref: pacs.028.001.02.json#/components/schemas/Document

